services:
  notiferry:
    restart: unless-stopped
    image: ghcr.io/omerktn/notiferry:latest
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      NOTIFERRY_TELEGRAM_BOT_TOKEN: "${NOTIFERRY_TELEGRAM_BOT_TOKEN:?export the bot token first}"
    volumes:
      - ./notiferry.yaml:/notiferry.yaml:ro
    command: ["--config", "/notiferry.yaml"]
